Name: "My Application"
Host: "127.0.0.1"
Port: 3366
Version: "1.0.0"


MysqlConf:
  host: "127.0.0.1"
  port: 3306
  database: "tang"
  username: "root"
  password: "root"
  charset: "utf8mb4"


RedisConf:
  addr: "127.0.0.1:6379"
  password: ""
  db: 0

#可以配置多个Redis连接
Redis:
  default:
    addr: "127.0.0.1:6379"
    password: ""
    db: 0
  cache:
    addr: "127.0.0.1:6379"
    password: ""
    db: 1